version: 2.1

jobs:

  checkout:
    docker:
      - image: alpine/git
    working_directory: /home/circleci/clojure-expectations/expectations-mode/
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - clojure-expectations/expectations-mode

  package-lint:
    docker:
      - image: camsaul/docker-emacs-package-lint
    working_directory: /home/circleci/clojure-expectations/expectations-mode/
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run:
          name: Run package-lint
          command: emacs -Q -nw -batch -l /usr/local/package-lint.el -f package-lint-batch-and-exit expectations-mode.el

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - package-lint:
          requires:
            - checkout
