version: 2.1

jobs:

  checkout:
    docker:
      - image: alpine/git
    working_directory: /home/circleci/clojure-expectations/expectations-mode/
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - clojure-expectations/expectations-mode

  # install-cider:
  #   docker:
  #     - image: camsaul/docker-emacs-package-lint
  #   working_directory: /home/circleci/clojure-expectations/expectations-mode/
  #   steps:
  #     - attach_workspace:
  #         at: /home/circleci/
  #     - restore_cache:
  #         keys:
  #           - cider-{{ .Branch }}-{{ .Revision }}
  #           - cider-{{ .Branch }}
  #           - cider-
  #     - run:
  #         name: Install CIDER
  #         command: emacs -Q -nw -batch -l /home/circleci/clojure-expectations/expectations-mode/.circleci/install-cider.el
  #         no_output_timeout: 5m
  #     - save_cache:
  #         key: cider-{{ .Branch }}-{{ .Revision }}
  #         paths:
  #           - /home/emacs/.emacs.d/elpa
  #     - persist_to_workspace:
  #         root: /home/emacs/
  #         paths:
  #           - .emacs.d/elpa

  package-lint:
    docker:
      - image: camsaul/docker-emacs-package-lint
    working_directory: /home/circleci/clojure-expectations/expectations-mode/
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run:
          name: Install cider locally & run package-lint
          command: emacs -Q -nw -batch -l /usr/local/package-lint.el -f package-lint-batch-and-exit expectations-mode.el
          no_output_timeout: 5m

workflows:
  version: 2
  build:
    jobs:
      - checkout
      # - install-cider:
      #     requires:
      #       - checkout
      - package-lint:
          requires:
            # - install-cider
