version: 2.1

########################################################################################################################
#                                                      EXECUTORS                                                       #
########################################################################################################################

executors:
  default:
    working_directory: /home/circleci/camsaul/expectations-mode/
    docker:
      - image: xueyouchao/docker-alpine-emacs


########################################################################################################################
#                                                       COMMANDS                                                       #
########################################################################################################################

jobs:

  checkout:
    executor: default
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - camsaul/expectations-mode

  fetch-package-lint:
    executor: default
    steps:
      - restore_cache:
          keys:
            - package-lint-{{ .Branch }}-{{ .Revision }}
            - package-lint-{{ .Branch }}
            - package-lint-
      - run: git clone https://github.com/purcell/package-lint.git /home/circleci/package-lint
      - save_cache:
          key: package-lint-{{ .Branch }}
          paths:
            - /home/circleci/package-lint/.git
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - package-lint

  package-lint:
    executor: default
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run:
          name: Run package-lint
          command: emacs

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - fetch-package-lint
      - package-lint:
          requires:
            - checkout
            - fetch-package-lint
